export const QueryKeys = {
  ProfileGetAll: "ProfileGetAll",
  UserGetById: "UserGetById",
  UserGetAll: "UserGetAll",
  CategoryGetAll: "CategoryGetAll",
  EmployeeGetAll: "EmployeeGetAll",
  DaysOfAttendance: "DaysOfAttendance",
  ScheduleGetSchedule: "ScheduleGetSchedule",
  AppointmentGetByUserId: "AppointmentGetByUserId",
  AppointmentGetById: "AppointmentGetById",
  WorkingHourGetAll: "WorkingHourGetAll",
  PaymentGetMethods: "PaymentGetMethods",
  AppointmentGetAll: "AppointmentGetAll",
  FeedbackGetById: "FeedbackGetById",
};
